GET http://localhost:3000/personal/index.html

###

POST http://localhost:3000/personal/form
Content-Type: application/json

{
    "firstName": "Joshua",
    "lastName": "Cohen",
    "emailAddress": "joshcohen8020@gmail.com",
    "description": "Hello There"
}

###
GET http://localhost:3000/personal/forms

###

GET http://localhost:3000/personal/formsDate?date='2-21-2023'